language: r
sudo: false
cache: packages
r:
  - release
  - devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0

warnings_are_errors: true
r_check_args: "--as-cran --run-donttest"

r_packages:
  - roxygen2

before_install:
  - cd aslib
